---
name: Publish container

on:
  workflow_dispatch: {}
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - DOCKERFILE
      - config/**
      - scripts/**

jobs:
  build-push:
    if: github.repository == 'arthurgeek/vaultwarden-fly-template'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Login to ghcr
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Container meta
        id: meta
        uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e # v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw, value=latest, enable={{is_default_branch}}
            type=semver, pattern={{version}}
            type=ref, event=branch
            type=ref, event=tag
            type=ref, event=pr

      - name: Build and push to ghcr
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
